$(document).ready(
    function() {
        $(function(){
            $("body").on("click","div.email_current", 
                function(){
                    $('.email_edit').toggle();   
                    $('.email_current').toggle(); 
                }
            );
        });
        $(function(){
            $("body").on("click","span.email_cancel", 
                function(){
                    $('.email_edit').toggle();   
                    $('.email_current').toggle(); 
                }
            );
        });  
               $(function(){
            $("body").on("click","div.summary_current", 
                function(){
                    $('.summary_edit').toggle();   
                    $('.summary_current').toggle(); 
                }
            );
        });
        $(function(){
            $("body").on("click","span.summary_cancel", 
                function(){
                    $('.summary_edit').toggle();   
                    $('.summary_current').toggle(); 
                }
            );
        });  
        
        $(function(){
            $("body").on("click","div.location_current", 
                function(){
                    $('.location_edit').toggle();   
                    $('.location_current').toggle(); 
                }
            );
        });
        $(function(){
            $("body").on("click","span.location_cancel", 
                function(){
                    $('.location_edit').toggle();   
                    $('.location_current').toggle(); 
                }
            );
        });   
        $(function(){
            $("body").on("click","div.printer_current", 
                function(){
                    $('.printer_edit').toggle();   
                    $('.printer_current').toggle(); 
                }
            );
        });
        $(function(){
            $("body").on("click","span.printer_cancel", 
                function(){
                    $('.printer_edit').toggle();   
                    $('.printer_current').toggle(); 
                }
            );
        });
        $(function(){
            $("body").on("click","div.slicer_current", 
                function(){
                    $('.slicer_edit').toggle();   
                    $('.slicer_current').toggle(); 
                }
            );
        });
        $(function(){
            $("body").on("click","span.slicer_cancel", 
                function(){
                    $('.slicer_edit').toggle();   
                    $('.slicer_current').toggle(); 
                }
            );
        });        
        $(function(){
            $("body").on("click","div.software_current", 
                function(){
                    $('.software_edit').toggle();   
                    $('.software_current').toggle(); 
                }
            );
        });
        $(function(){
            $("body").on("click","span.software_cancel", 
                function(){
                    $('.software_edit').toggle();   
                    $('.software_current').toggle(); 
                }
            );
        });                  
    }


);
//end of line